"repository rule for generating a dependency graph from a lockfile."

load(":lockfile.bzl", "lockfile")
load(":package_set.bzl", "package_closure")
load(":starlark_codegen_utils.bzl", "starlark_codegen_utils")
load(":util.bzl", "util")
load(":version.bzl", version_lib = "version")

_ROOT_BUILD_TMPL = """\
"Generated by rules_distroless. DO NOT EDIT."

load("@rules_distroless//apt:defs.bzl", "apt_package_set", "dpkg_status")
load("@rules_distroless//distroless:defs.bzl", "flatten")

exports_files(['lock.json'])

# Map Debian architectures to platform CPUs.
#
# For more info on Debian architectures, see:
#     * https://wiki.debian.org/SupportedArchitectures
#     * https://wiki.debian.org/ArchitectureSpecificsMemo
#     * https://www.debian.org/releases/stable/amd64/ch02s01.en.html#idm186
#
# For more info on Bazel's platforms CPUs see:
#     * https://github.com/bazelbuild/platforms/blob/main/cpu/BUILD
_ARCHITECTURE_MAP = {{
    "amd64": "x86_64",
    "arm64": "arm64",
    "ppc64el": "ppc64le",
    "mips64el": "mips64",
    "s390x": "s390x",
    "i386": "x86_32",
    "armhf": "armv7e-mf",
    "all": "all",
}}

_ARCHITECTURES = {architectures}

[
   config_setting(
    name = os + "_" + arch,
    constraint_values = [
       "@platforms//os:" + os,
       "@platforms//cpu:" + _ARCHITECTURE_MAP[arch],
    ],
    visibility = ["//:__subpackages__"],
  )
  for os in ["linux"]
  for arch in _ARCHITECTURES
]


# List of installed packages. For now it's private.
_PACKAGES = {packages}

apt_package_set(
    name = "package_set",
    architecture = select({package_set_architectures}),
    dependency_set = {dependency_set},
    lock = ":lock.json",
    package_records = select({package_set_metadata}),
    data = select({package_set_data}),
    control = select({package_set_control}),
    visibility = ["//visibility:public"],
)

# Creates /var/lib/dpkg/status with installed package information.
dpkg_status(
    name = "dpkg_status",
    controls = select({{
        "//:linux_%s" % arch: ["//%s/%s:control" % (package, arch) for package in packages]
        for arch, packages in _PACKAGES.items()
    }}) if _PACKAGES else {{}},
    visibility = ["//visibility:public"],
)

filegroup(
    name = "packages",
    srcs = select({{
        "//:linux_%s" % arch: ["//%s/%s" % (package, arch) for package in packages]
        for arch, packages in _PACKAGES.items()
    }}) if _PACKAGES else {{}},
    visibility = ["//visibility:public"],
)


# A filegroup that contains all the packages and the dpkg status file.
filegroup(
    name = "{target_name}",
    srcs = [
        ":dpkg_status",
        ":packages",
    ],
    visibility = ["//visibility:public"],
)

flatten(
    name = "flat",
    tars = [
        "{target_name}",
    ],
    deduplicate = True,
    visibility = ["//visibility:public"],
)
"""

_PACKAGE_TEMPLATE = '''\
"""Generated by rules_distroless. DO NOT EDIT."""

NO_MATCH_ERROR="""
Package "{target_name}" is not available for the current target platform.

Available Platforms: {available_platforms}

- Set `--platforms` on the command line.
- Perform a transition to one of the available platforms
"""

alias(
    name = "data",
    actual = select({data_targets}, no_match_error = NO_MATCH_ERROR),
    visibility = ["//visibility:public"],
)

alias(
    name = "control",
    actual = select({control_targets}, no_match_error = NO_MATCH_ERROR),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "{target_name}",
    srcs = select({deps}, no_match_error = NO_MATCH_ERROR) + [":data"],
    visibility = ["//visibility:public"],
)

{extra}
'''

_DEB_CC_IMPORT = """
alias(
    name = "{target_name}",
    actual =  select({selects}),
    visibility = ["//visibility:public"],
)
"""

# Computes the `@repo//:data` labels a package's per-architecture BUILD.bazel
# should depend on for the given architecture.
#
# Avoids mixing architectures: a dependency is only included if it was built
# for this exact architecture, or is architecture-independent ("all"). Without
# this scoping, a package's `depends_on` (which spans every architecture the
# lockfile knows about) would leak foreign-architecture deps into a single
# architecture's target, causing file duplication that confuses `flatten`.
def package_deps_for_architecture(packages, package, architecture, mergedusr = False, repo_prefix = ""):
    return [
        "@" + repo_prefix + util.package_repo_name(dep_key, mergedusr = mergedusr) + "//:data"
        for dep_key in package["depends_on"]
        if packages[dep_key]["architecture"] in [architecture, "all"]
    ]

RESERVED_TEMPLATE_VARIABLES = [
    "arch",
    "control_targets",
    "data_targets",
    "deps",
    "name",
    "repo_name",
    "sha256",
    "src",
    "suite",
    "target_name",
    "urls",
    "version",
]

def check_template_variable_collision(variables, reserved = RESERVED_TEMPLATE_VARIABLES):
    """Checks if any variable name in variables collides with reserved names.

    Args:
        variables: dictionary or iterable of variable names.
        reserved: list or iterable of reserved variable names.

    Returns:
        The first colliding variable name found, or None.
    """
    for key in variables:
        if key in reserved:
            return key
    return None

def resolve_package_template(package_name, package_templates, default_template):
    """Resolves the package template and additional variables for a package name.

    Args:
        package_name: name of the deb package.
        package_templates: list of template dictionaries.
        default_template: default template string to use if no pattern matches.

    Returns:
        A tuple of (template_string, additional_variables_dict).
    """
    for entry in package_templates:
        for pattern in entry.get("packages", []):
            if util.glob_match(pattern, package_name):
                return (entry["template"], entry.get("additional_variables", {}))
    return (default_template, {})

def _translate_dependency_set_impl(rctx):
    default_package_template = rctx.read(rctx.attr.package_template)
    package_templates = json.decode(rctx.attr.package_templates) if rctx.attr.package_templates else []
    lockf = lockfile.from_json(rctx, rctx.attr.lock_content)

    packages = lockf.packages()
    dependency_sets = lockf.dependency_sets()
    dependency_set = dependency_sets[rctx.attr.depset_name]

    packages_to_architectures = {}

    # Maps each architecture to the list of package names installed for it.
    # Used to populate the root repo's _PACKAGES table.
    architectures_to_package_names = {}

    # Maps a package coordinates key (e.g. `(<package name>, <architecture>)` to its version.
    #
    # It is possible to specify multiple versions of a single dependency for a single architecture in a dependency set.
    # In those cases, we want to hard-error.
    package_coords_to_versions = {}

    package_set_architectures = {}
    package_set_metadata = {}
    package_set_data = {}
    package_set_control = {}

    for architecture in dependency_set["sets"].keys():
        condition = "//:linux_" + architecture
        closure = package_closure(
            packages,
            [key + "=" + version for key, version in dependency_set["sets"][architecture].items()],
            architecture,
        )
        package_set_architectures[condition] = architecture
        package_set_metadata[condition] = {key: json.encode(package) for key, package in closure.items()}
        package_set_data[condition] = {
            "@" + rctx.attr.repo_prefix + util.package_repo_name(key, mergedusr = rctx.attr.mergedusr) + "//:data": key
            for key in closure
        }
        package_set_control[condition] = {
            "@" + rctx.attr.repo_prefix + util.package_repo_name(key, mergedusr = rctx.attr.mergedusr) + "//:control": key
            for key in closure
        }
        architectures_to_package_names[architecture] = []

        for (short_key, version) in dependency_set["sets"][architecture].items():
            package_key = short_key + "=" + version
            repo_name = rctx.attr.repo_prefix + util.package_repo_name(package_key, mergedusr = rctx.attr.mergedusr)
            package = packages[package_key]
            package_name = package["name"]

            architectures_to_package_names[architecture].append(package_name)

            source_version = version
            package_coords = (package_name, architecture)
            recorded_version = package_coords_to_versions.setdefault(package_coords, source_version)
            if recorded_version != source_version:
                fail("""Two different source versions detected for package `{name}:{arch}` : {v1} and {v2}.
This usually means that a distribution ships different versions of this dependency for different architectures.

Please unify the versions manually, or use separate `apt.install` calls (with distinct `dependency_set` names) for each version of the dependency.
""".format(name = package_name, arch = architecture, v1 = recorded_version, v2 = source_version))

            # Keyed by package name (not name+version): a package rebuilt with a
            # different binNMU per architecture is a single target whose data,
            # control and deps are selected per architecture.
            packages_to_architectures.setdefault(
                package_name,
                struct(
                    name = package_name,
                    architectures = {},
                ),
            ).architectures[architecture] = package_key

            (tmpl, additional_variables) = resolve_package_template(
                package_name,
                package_templates,
                default_package_template,
            )

            format_vars = {
                "target_name": architecture,
                "data_targets": '"@%s//:data"' % repo_name,
                "control_targets": '"@%s//:control"' % repo_name,
                "src": '"@%s//:data"' % repo_name,
                "deps": package_deps_for_architecture(packages, package, architecture, mergedusr = rctx.attr.mergedusr, repo_prefix = rctx.attr.repo_prefix),
                "urls": package["urls"],
                "name": package["name"],
                "version": package["version"],
                "suite": package["suite"],
                "arch": package["architecture"],
                "sha256": package["sha256"],
                "repo_name": repo_name,
            }
            collision = check_template_variable_collision(additional_variables, format_vars)
            if collision:
                fail("apt.package_template: additional variable '{key}' for package '{name}' conflicts with built-in template variable.".format(
                    key = collision,
                    name = package_name,
                ))
            format_vars.update(additional_variables)

            rctx.file(
                "%s/%s/BUILD.bazel" % (package["name"], architecture),
                tmpl.format(**format_vars),
            )

    for (_, info) in packages_to_architectures.items():
        package_name = info.name

        architectures = info.architectures.keys()

        extra = ""
        if package_name.endswith("-dev"):
            target_name = package_name.removesuffix("-dev")
            extra = _DEB_CC_IMPORT.format(
                target_name = target_name,
                selects = starlark_codegen_utils.to_dict_attr({
                    "//:linux_%s" % architecture: "@%s//:%s" % (rctx.attr.repo_prefix + util.package_repo_name(package_key, mergedusr = rctx.attr.mergedusr), target_name)
                    for (architecture, package_key) in info.architectures.items()
                }),
            )

        rctx.file(
            "%s/BUILD.bazel" % package_name,
            _PACKAGE_TEMPLATE.format(
                target_name = package_name,
                data_targets = starlark_codegen_utils.to_dict_attr({
                    "//:linux_%s" % architecture: "//%s/%s:data" % (package_name, architecture)
                    for architecture in architectures
                }),
                control_targets = starlark_codegen_utils.to_dict_attr({
                    "//:linux_%s" % architecture: "//%s/%s:control" % (package_name, architecture)
                    for architecture in architectures
                }),
                deps = starlark_codegen_utils.to_dict_list_attr({
                    "//:linux_%s" % architecture: ["//%s/%s" % (package_name, architecture)]
                    for architecture in architectures
                }),
                extra = extra,
                available_platforms = " ".join([
                    "linux/" + arch
                    for arch in architectures
                ]),
            ),
        )

    rctx.file("lock.json", rctx.attr.lock_content)
    rctx.file("BUILD.bazel", _ROOT_BUILD_TMPL.format(
        target_name = util.get_repo_name(rctx.attr.name),
        packages = starlark_codegen_utils.to_dict_list_attr(architectures_to_package_names),
        architectures = starlark_codegen_utils.to_list_attr(dependency_set["sets"].keys()),
        dependency_set = repr(rctx.attr.depset_name),
        package_set_architectures = repr(package_set_architectures),
        package_set_metadata = repr(package_set_metadata),
        package_set_data = repr(package_set_data),
        package_set_control = repr(package_set_control),
    ))

translate_dependency_set = repository_rule(
    implementation = _translate_dependency_set_impl,
    attrs = {
        "depset_name": attr.string(doc = "INTERNAL: DO NOT USE"),
        "lock_content": attr.string(doc = "INTERNAL: DO NOT USE"),
        "repo_prefix": attr.string(doc = "INTERNAL: Namespace for independent checked locks."),
        "mergedusr": attr.bool(default = False, doc = "INTERNAL: Whether package layers were normalized with merged-/usr semantics."),
        "package_template": attr.label(default = "//apt/private:package.BUILD.tmpl"),
        "package_templates": attr.string(default = "[]", doc = "INTERNAL: JSON-encoded list of package template configurations"),
    },
)
